version: "3.8"

services:
  web:
    build: .
    image: oluwatofunmi/question-answer:v1
    container_name: flask_app
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=2MXNiagoSl6N3TobdDg8qwqJWVknJxYD
      - POSTGRES_DB=backend_intern
      - DATABASE_URL=postgresql://admin:2MXNiagoSl6N3TobdDg8qwqJWVknJxYD@dpg-ctir55t2ng1s73bej3c0-a.oregon-postgres.render.com/backend_intern
      - FLASK_ENV=development
    env_file:
      - .env
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0
  

